import 'dotenv/config';
import express from 'express'; import multer from 'multer'; import crypto from 'crypto'; import Razorpay from 'razorpay'; import {createClient} from '@supabase/supabase-js';
const app=express(), upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024}});
const supabase=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY); const razor=new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET});
app.post('/api/webhook/razorpay',express.raw({type:'application/json'}),async(req,res)=>{try{const sig=req.headers['x-razorpay-signature'];const expected=crypto.createHmac('sha256',process.env.RAZORPAY_WEBHOOK_SECRET).update(req.body).digest('hex');if(!sig||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(sig)))return res.status(400).send('bad signature');const event=JSON.parse(req.body.toString());if(event.event==='payment.captured'){const p=event.payload.payment.entity;await supabase.from('orders').update({status:'paid',razorpay_payment_id:p.id}).eq('razorpay_order_id',p.order_id)}res.json({ok:true})}catch(e){res.status(400).send('invalid')}});
app.use(express.json()); app.use(express.static('public'));
async function products(){const {data,error}=await supabase.from('products').select('id,programme,code,title,price,active').eq('active',true).order('programme').order('code');if(error)throw error;return data}
app.get('/api/products',async(_,res)=>{try{res.json({products:await products()})}catch(e){res.status(500).json({error:e.message})}});
function admin(req,res,next){if(req.headers['x-admin-secret']!==process.env.ADMIN_SECRET)return res.status(401).json({error:'Admin authentication required'});next()}
app.get('/api/admin/products',admin,async(_,res)=>{const {data,error}=await supabase.from('products').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json({products:data})});
app.post('/api/admin/products',admin,upload.single('pdf'),async(req,res)=>{try{if(!req.file||req.file.mimetype!=='application/pdf')throw Error('PDF file required');const {programme,code,title,price}=req.body;if(!programme||!code||!title||!(Number(price)>0))throw Error('Programme, code, title and valid price are required');const path=`${crypto.randomUUID()}.pdf`;const up=await supabase.storage.from('assignment-pdfs').upload(path,req.file.buffer,{contentType:'application/pdf',upsert:false});if(up.error)throw up.error;const {data,error}=await supabase.from('products').insert({programme,code:code.toUpperCase(),title,price:Number(price),storage_path:path,active:true}).select().single();if(error){await supabase.storage.from('assignment-pdfs').remove([path]);throw error}res.json({product:data})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/admin/products/:id',admin,async(req,res)=>{const {data,error}=await supabase.from('products').select('storage_path').eq('id',req.params.id).single();if(error)return res.status(404).json({error:error.message});await supabase.storage.from('assignment-pdfs').remove([data.storage_path]);const d=await supabase.from('products').delete().eq('id',req.params.id);if(d.error)return res.status(500).json({error:d.error.message});res.json({ok:true})});
app.post('/api/orders',async(req,res)=>{try{const {data:p,error}=await supabase.from('products').select('*').eq('id',req.body.product_id).eq('active',true).single();if(error)throw Error('Product not found');const order=await razor.orders.create({amount:Math.round(Number(p.price)*100),currency:'INR',receipt:crypto.randomUUID(),notes:{product_id:p.id}});await supabase.from('orders').insert({product_id:p.id,razorpay_order_id:order.id,amount:order.amount,status:'created'});res.json({order_id:order.id,amount:order.amount,key_id:process.env.RAZORPAY_KEY_ID,product:{title:p.title}})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/orders/verify',async(req,res)=>{try{const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body;const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(razorpay_order_id+'|'+razorpay_payment_id).digest('hex');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(razorpay_signature)))throw Error('Invalid payment signature');const {data:o,error}=await supabase.from('orders').update({razorpay_payment_id,status:'paid'}).eq('razorpay_order_id',razorpay_order_id).select('id,product_id').single();if(error)throw error;const token=crypto.randomBytes(32).toString('hex');await supabase.from('download_tokens').insert({token,order_id:o.id,expires_at:new Date(Date.now()+15*60*1000).toISOString()});res.json({token})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/download/:token',async(req,res)=>{try{const {data:t,error}=await supabase.from('download_tokens').select('expires_at,orders(product_id,products(storage_path,title))').eq('token',req.params.token).single();if(error||!t||new Date(t.expires_at)<new Date())return res.status(410).send('Download link expired.');const path=t.orders.products.storage_path;const {data,urlError}=await supabase.storage.from('assignment-pdfs').createSignedUrl(path,300,{download:`${t.orders.products.title}.pdf`});if(urlError)throw urlError;res.redirect(data.signedUrl)}catch(e){res.status(404).send('Download unavailable.')}});

const port=process.env.PORT||3000;app.listen(port,()=>console.log(`Shiv Assignments running on ${port}`));
